### ISSUE TITLE
Support TFLITE's mobilenetv2, squeezenetv1.1 bench?

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mobile-ai-bench#17]
Thanks in advance.

**Comment by lydoc** [comment]
We will support TFLITE's mobilenetv2 and some quantized models later. But for the squeezenet,  TFLITE supports [squeezenet v1.10](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md#image-classification-float-models) officially which is different from squeezenet v1.11 supported in MACE/NCNN/SNPE, so we do not support squeezenet in TFLITE in this project.

**Comment by lydoc** [comment]
@ysh329 Sorry, a slip of the tongue just now, I mean the tensorflow lite host only squeezenet v1.0 tflite model, if you want benchmark squeezenet v1.1 in TFLITE, you can fellow these steps: https://github.com/XiaoMi/mobile-ai-bench#adding-a-model-to-run-on-existing-framework

**Comment by ysh329** [comment]
@lydoc Greatly thanks. Besides, I saw many mobilenetv2 models in [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md#image-classification-float-models) you gave. Which mobilenetv2 is general baseline mobilenetv2, that bench used? 😿

**Comment by lydoc** [comment]
@ysh329 I guess what you might say is different versions of Mobilenet_V1. We use Mobilenet_V1_1.0_224.

**Comment by ysh329** [comment]
Thanks. 🙇
