### ISSUE TITLE
Kirin970 GPU much slower than Snapdragon 845

### ISSUE THREAD

**Issue by achigeor** [XiaoMi/mobile-ai-bench#23]
Are there any insights as to why kirin 970 GPU is that much slower than Snapdragon 845? The compute capabilities should be around the same for these two SoCs right? 

For example mobilenetsv2 benchmark runs at `~10ms` for `sdm845` and `47.597ms` for `kirin970` (optimized). I also see big differences in my custom model. On a `sdm845` I get around `75ms`, while on `kirin980` I get around `250ms`.

Is it because snapdragon is actually that much faster, or because of how Mace ops / kernels are implemented? If it's the latter, what would be a good place to start working on possible optimizations?
Would you expect improvements if ARM Compute is used for ARM SoCs?

**Comment by llhe** [comment]
@achigeor 
See the reply here: https://github.com/XiaoMi/mace/issues/1#issuecomment-462580008

Welcome to post the results for ARM Compute Library to make the comparison, and adding an executor will be highly appreciated.
