### ISSUE TITLE
Has any benchmark result for NNlib

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mobile-ai-bench#24]
Hi, all!

Has any benchmark result for nnlib with mace, ncnn or etc? Besides, I wanna ask which performance is better between nnlib and SNPE?

Thanks in advance.

**Comment by liyinhgqw** [comment]
I don't think ncnn has support nnlib yet. For Mace and SNPE, they have almost the same performance. For model prepare time, Mace is better.

**Comment by ysh329** [comment]
Excuse, I'm little confused, what's the nnlib? Is an Android common API for deep learning? Does it have raw implementation?

**Comment by lee-bin** [comment]
It's a library which can be found in https://developer.qualcomm.com/software/hexagon-dsp-sdk as hexagon nn, you can get all the information from Hexagon DSP SDK.
So basically, it's for Hexagon DSP and is usually integrated with deep learning inference engines, e.g., SNPE, MACE.
The benchmark results of DSP of MACE and SNPE all use nnlib.

**Comment by ysh329** [comment]
Greatly thank you, bin.

Besides, I wanna ask what's the relationship between DSP/AIP runtimes of SNPE and Hexagon NN. Of course, I wanna know the performance between them. Any idea?

**Comment by lee-bin** [comment]
DSP of SNPE is based on Hexagon NN, so its performance is also based on Hexagon NN.

**Comment by ysh329** [comment]
Greatly and always Thanks you ~~ bin
