### ISSUE TITLE
com_google_protobuf Build Error

### ISSUE THREAD

**Issue by newway1995** [XiaoMi/mobile-ai-bench#26]
/private/var/tmp/_bazel_slice/4dad7a7745975e897b9323b66e817b04/external/com_google_protobuf/BUILD:355:1: Linking of rule '@com_google_protobuf//:protoc' failed (Exit 1): cc_wrapper.sh failed: error executing command

**Comment by lee-bin** [comment]
Make sure your environment is the same with https://github.com/XiaoMi/mobile-ai-bench/blob/master/README.md#environment-requirement

**Comment by hanton** [comment]
hi @newway1995 , I have the same issue when running on Mac. 

Fixing it by turning on `build:cross_compile --distinct_host_configuration=true` in `tools/bazel.rc`
