### ISSUE TITLE
different benchmark methods for SNPE

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mobile-ai-bench#27]
Hi, I read docs from SNPE: https://developer.qualcomm.com/docs/snpe/benchmarking.html, found 3 methods calling SNPE:

1. C++ API
2. Python API
3. command 

I found using c++ API in mobile-ai-bench. Is this C++ method fastest and accurate?

Thanks in advance.

**Comment by lee-bin** [comment]
Yes

**Comment by ysh329** [comment]
Thanks~
