### ISSUE TITLE
SNPE correctness problem

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mobile-ai-bench#29]
Hi, all,

I recently tested SNPE according its doc not mobile-ai-bench, and found its results are wrong for mobilenetv1, v2 on Snapdragon 835 (check using its Python script`models/alexnet/scripts/show_alexnet_classifications.py`).

Thus, I wanna ask do you verify the correctness? Thanks in advance.

**Comment by lee-bin** [comment]
I'm not familiar with `models/alexnet/scripts/show_alexnet_classifications.py`.
What did you test? If you used SNPE tools to quantize MobileNetV1 or MobileNetV2, accuracy should be very low. But other than that, accuracy is pretty close to the original model.

**Comment by ysh329** [comment]
I tested mobilenet and its accruacy of quantitzed mobilenet indeed are wrong. Thanks~
