### ISSUE TITLE
mix2解锁：账号申请地区查询失败

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mobile-ai-bench#31]
解锁时候，在win上使用官方提供的工具，提示：账号申请地区查询失败。

- [参考不少miui论坛里的问题和回复，并没找到官方对该问题的解答](http://www.miui.com/search.php?mod=forum&searchid=11890120&orderby=lastpost&ascdesc=desc&searchsubmit=yes&kw=%E8%B4%A6%E5%8F%B7%E7%94%B3%E8%AF%B7%E5%9C%B0%E5%8C%BA%E6%9F%A5%E8%AF%A2%E5%A4%B1%E8%B4%A5&month=&refineSearch=0)

期待您的答复~感谢

**Comment by ysh329** [comment]
是否是因为等待的时间需要72小时?但并没有相关提示，而且我也在上次解锁另一台小米手机的时候获得了解锁权限，这次距离上次间隔时间大于1个月。

**Comment by yejw5** [comment]
这个具体上MIUI论坛咨询吧

**Comment by ysh329** [comment]
我看也不会有官方同学给回复，我附加的超链接那么多现骨干问题，也没有人解答……

**Comment by lee-bin** [comment]
１、欢迎使用本项目:)
２、我们对你的遭遇表示很遗憾。。。
但是...
３、在此问非Mobile-AI-Bench本身的问题不合适，会干扰其他用户使用本项目。

**Comment by ysh329** [comment]
好的，感谢~~

**Comment by touchmii** [comment]
> 解锁时候，在win上使用官方提供的工具，提示：账号申请地区查询失败。
> 
> * [参考不少miui论坛里的问题和回复，并没找到官方对该问题的解答](http://www.miui.com/search.php?mod=forum&searchid=11890120&orderby=lastpost&ascdesc=desc&searchsubmit=yes&kw=%E8%B4%A6%E5%8F%B7%E7%94%B3%E8%AF%B7%E5%9C%B0%E5%8C%BA%E6%9F%A5%E8%AF%A2%E5%A4%B1%E8%B4%A5&month=&refineSearch=0)
> 
> 期待您的答复~感谢
可能是电脑开了网络代理，把代理工具关闭就好了，我遇到的就是这个情况。
