### ISSUE TITLE
Weak Cryptographic Hash

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [XiaoMi/mobile-ai-bench#34]
https://github.com/XiaoMi/mobile-ai-bench/blob/6798ccd22e9148934350e886a1b0b2b50037e53b/aibench/python/utils/bench_utils.py#L19

Weak cryptographic hashes cannot guarantee data integrity and should not be used in security-critical contexts.It is recommended to use SHA-224, SHA-256，SHA-384

**Comment by lee-bin** [comment]
Thanks for your advice, we use MD5 because some older devices don't have built-in SHA command.
