### ISSUE TITLE
能支持nvidia相关平台么

### ISSUE THREAD

**Issue by TUT-jiayou** [XiaoMi/mobile-ai-bench#36]
你好：
我有一些问题想请教以下

1。是否可以根据Readme指导中，添加另外一种AI框架，来实现对nvidia支持
2。测试使用的这些模型，是跟公开的模型是完全一样的么，若，直接将这些模型在nvidia平台上推理，得到的推理时间是比较公平的么
3。若现在不支持的话，之后会支持相关的nvidia平台么

多谢

**Comment by lu229** [comment]
@TUT-jiayou 回复如下：
1，可以的
2，与公开的模型是一样的；mobile-ai-bench的代码对任何框架、模型的调用和计时代码都是一样的，从这个意义上看，对每个框架、模型都是公平的
3，mobile-ai-bench主要是支持移动端的测试，NVIDIA在移动端的硬件比较少，我们支持的概率不大。

**Comment by TUT-jiayou** [comment]
嗯嗯，多谢。目前nvidia也推出了一些端测的设备，TX2， nano，之后这些mobile的SoCs也可以应用到一些新的场景下，而不只是mobile ，我觉得对于其他平台AI 算力的测量，可以更好的拓展这个工具的适用场景，也能够促进更多的开发者，投入到这个工具的开发。

**Comment by lu229** [comment]
@TUT-jiayou 非常感谢您的建议，我们这边主要是人手的问题，我们热烈欢迎开发者的commit。
