### ISSUE TITLE
can't support aarch64_linux  SNPE

### ISSUE THREAD

**Issue by TUT-jiayou** [XiaoMi/mobile-ai-bench#40]
Hi, all 
system info
```
devices sda845
abi  aarch64
os ubuntu 16.04
```
when I run the command ```bash tools/benchmark.sh --benchmark_option=Performance --target_abis=aarch64 --executors=SNPE```
I get the error
```
(mobile-ai-bench_env) wang@ubuntu-pc:~/workspace/benchmark_tool/source_code/mobile-ai-bench$ bash tools/benchmark.sh --benchmark_option=Performance --target_abis=aarch64 --executors=SNPE
INFO: Found 1 target...
Target //aibench/python:benchmark up-to-date:
  bazel-bin/aibench/python/benchmark
INFO: Elapsed time: 0.169s, Critical Path: 0.00s
Find ssh device:sda845
Prepare to run models on aarch64
Skip device  which doesn't support current executors

```
I am so con confused why the executors can not run in the devices. Because I find the
```
cc_library(
    name = "snpe_aarch64",
    srcs = [
        "lib/aarch64-linux-gcc4.9/libSNPE.so",
        "lib/aarch64-linux-gcc4.9/libsymphony-cpu.so",
    ],
    deps = ["snpe_hdr"],
    visibility = ["//visibility:public"],
)
```
in the file named ```mobile-ai-bench/third_party/snpe/snpe.BUILD ```. 
thanks for your time.

**Comment by lee-bin** [comment]
Please read the [Note 1](https://github.com/XiaoMi/mobile-ai-bench#environment-requirement) part.

**Comment by TUT-jiayou** [comment]
I read the part, and modify the file ```WORKSPACE```
![Selection_006](https://user-images.githubusercontent.com/21277368/78151165-dceb8780-746a-11ea-8a68-a196530dee20.png)
And I try it in the  android  sda845, then it work very  good. 
My SNPE version is ``` snpe-1.25.1.310```.  This is maybe the version of SNPE, Can you give me the version 1.18.0.  I can't  find it. 
Thanks for your time.

**Comment by TUT-jiayou** [comment]
About the [Note 1](https://github.com/XiaoMi/mobile-ai-bench#environment-requirement), I can't find the  ```libgnustl_shared.so ```, So I don't copy it, and  I don't know where should copy to . 
```
new_local_repository(
    name = "snpe",
    build_file = "third_party/snpe/snpe.BUILD",
    path = "/path/to/snpe",
)
```
just the ```path```  ??

**Comment by TUT-jiayou** [comment]
And about the ```snpe-1.25.1.310```,  there is    
![Selection_007](https://user-images.githubusercontent.com/21277368/78152546-897a3900-746c-11ea-93e7-621166ebec0a.png)

in the directory ```snpe-sdk/lib```

**Comment by TUT-jiayou** [comment]
I try that through adb ,it can work. thanks for your help.
