### ISSUE TITLE
file libmace.zip md5 checksum not match

### ISSUE THREAD

**Issue by PennySHE** [XiaoMi/mobile-ai-bench#5]
Try to run mobile-ai-bench but libmace md5 checksum fail

~/xiaomi/mobile-ai-bench$ python tools/benchmark.py --output_dir=output --frameworks=all \
>                           --runtimes=all --model_names=all \
>                           --target_abis=armeabi-v7a,arm64-v8a
downloading libmace.zip...
file libmace.zip md5 checksum not match

**Comment by lee-bin** [comment]
Did you use the latest code? libmace.zip has been updated last week.

**Comment by PennySHE** [comment]
Thanks,  update to latest code and resolve this issue
$ git pull
Updating f8bf9ac..267f24b
Fast-forward
 aibench/BUILD             |  1 +
 aibench/executors/BUILD   |  4 +++-
 third_party/mace/BUILD    | 14 +++++++++-----
 tools/benchmark.py        | 15 ++++++++++++---
 tools/model_and_input.yml |  2 +-
 tools/sh_commands.py      | 19 +++++++++----------
 6 files changed, 35 insertions(+), 20 deletions(-)
