### ISSUE TITLE
Have docker image?

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mobile-ai-bench#7]
Thanks in advance.

**Comment by lee-bin** [comment]
You can use the MACE docker, full edition.
https://mace.readthedocs.io/en/latest/installation/using_docker.html

**Comment by ysh329** [comment]
@lee-bin Great!

**Comment by ysh329** [comment]
@lee-bin eh, have this repo's docker image?

**Comment by lee-bin** [comment]
We reuse MACE docker for MobileAIBench. So no dedicated docker image for MobileAIBench.

**Comment by ysh329** [comment]
@lee-bin Thanks 👍
